### ISSUE TITLE
Problem while lauching prometheus and the adapter

### ISSUE THREAD

**Issue by giovannifs** [kubernetes-sigs/prometheus-adapter#129]
Hi folks, 

We have developed a new scheduler for the kubernetes and used prometheus for keeping customized metrics required for this. By the end of June, we had a kubernetes cluster (version 1.9.6) configured with this new scheduler running and ok. We are trying to deploy a new cluster (also version 1.9.6) but the prometheus pod is going to **CrashLoopBackOff** status.

We were using **directxman12/k8s-prometheus-adapter-amd64:latest** image for adapter. We also had tried to use v0.2.1 image, which is the oldest tag (4 months) and closer to the image we used arround 5 months ago, but it does not work too. 

When I describe the prometheus pod, the last events are:

```bash
Events:
  Type     Reason   Age                From                          Message
  Normal   Pulling  23m (x37 over 2h)  kubelet, kubemaster-giovanni  pulling image "directxman12/k8s-prometheus-adapter-amd64:latest"
  Warning  BackOff  3m (x628 over 2h)  kubelet, kubemaster-giovanni  Back-off restarting failed container
```

When I check the log of **cm-adapter** container of prometheus pod, using the command:

```
kubectl logs -n prom prometheus-$HASH -c cm-adapter
```

The output is:

```bash
unknown flag: --rate-interval
Usage of /adapter:
unknown flag: --rate-interval
      --alsologtostderr                                         log to standard error as well as files
      --authentication-kubeconfig string                        kubeconfig file pointing at the 'core' kubernetes server with enough rights to create tokenaccessreviews.authentication.k8s.io.
      --authentication-skip-lookup                              If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from the cluster.
      --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 10s)
      --authorization-kubeconfig string                         kubeconfig file pointing at the 'core' kubernetes server with enough rights to create  subjectaccessreviews.authorization.k8s.io.
      --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
      --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
      --bind-address ip                                         The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank, all interfaces will be used (0.0.0.0 for all IPv4 interfaces and :: for all IPv6 interfaces). (default 0.0.0.0)
      --cert-dir string                                         The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided, this flag will be ignored. (default "apiserver.local.config/certificates")
      --client-ca-file string                                   If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.
      --config string                                           Configuration file containing details of how to transform between Prometheus metrics and custom metrics API resources
      --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
      --discovery-interval duration                             interval at which to refresh API discovery information
      --enable-swagger-ui                                       Enables swagger ui on the apiserver at /swagger-ui
      --http2-max-streams-per-connection int                    The limit that the server gives to clients for the maximum number of streams in an HTTP/2 connection. Zero means to use golang's default.
      --lister-kubeconfig string                                kubeconfig file pointing at the 'core' kubernetes server with enough rights to list any described objects
      --log-flush-frequency duration                            Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at traceLocation                          when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                                          If non-empty, write log files in this directory
      --logtostderr                                             log to standard error instead of files (default true)
      --metrics-relist-interval duration                        interval at which to re-list the set of all available metrics from Prometheus (default 10m0s)
      --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
      --prometheus-auth-config string                           kubeconfig file used to configure auth when connecting to Prometheus.
      --prometheus-auth-incluster                               use auth details from the in-cluster kubeconfig when connecting to prometheus.
      --prometheus-url string                                   URL for connecting to Prometheus. (default "https://localhost")
      --requestheader-allowed-names strings                     List of client certificate common names to allow to provide usernames in headers specified by --requestheader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.
      --requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.
      --requestheader-extra-headers-prefix strings              List of request header prefixes to inspect. X-Remote-Extra- is suggested. (default [x-remote-extra-])
      --requestheader-group-headers strings                     List of request headers to inspect for groups. X-Remote-Group is suggested. (default [x-remote-group])
      --requestheader-username-headers strings                  List of request headers to inspect for usernames. X-Remote-User is common. (default [x-remote-user])
      --secure-port int                                         The port on which to serve HTTPS with authentication and authorization. If 0, don't serve HTTPS at all. (default 443)
      --stderrthreshold severity                                logs at or above this threshold go to stderr (default 2)
      --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). If HTTPS serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory specified by --cert-dir.
      --tls-cipher-suites strings                               Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be use.  Possible values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA
      --tls-min-version string                                  Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12
      --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com". (default [])
  -v, --v Level                                                 log level for V logs
      --vmodule moduleSpec                                      comma-separated list of pattern=N settings for file-filtered logging
```

The cluster that we had working by the end of June also is with this same problem. 

Does anyone know if the **directxman12/k8s-prometheus-adapter-amd64:latest** image is not compatible with kubernetes v1.9.6 anymore? Or have some idea how to solve this problem?

Additionaly, does anyone have a copy of **directxman12/k8s-prometheus-adapter-amd64** image from the end of June that could make available? I could test using an older version of this image.

We would appreciate any help.

**Comment by giovannifs** [comment]
Hi folks, 

Ttrying to solve our problem, we commented the argument ```rate-interval=30s``` in the **prom-adapter.deployment.yaml**, but the error continues. However, the message in the log is different now.

The log message is:

```bash
F1114 13:16:23.524267       1 adapter.go:190] unable to load metrics discovery config: no metrics discovery configuration file specified (make sure to use --config)
```

Our **prom-adapter.deployment.yaml** is:

```bash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        # based on your Prometheus config above, this tells prometheus
        # to scrape this pod for metrics on port 9091 at "/metrics"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: prom-cm-adapter
      containers:
      - image: directxman12/k8s-prometheus-adapter-amd64:latest
        name: cm-adapter
        args:
        - --secure-port=6443
        - --logtostderr=true
        - --tls-cert-file=/var/run/serving-certs/tls.crt
        - --tls-private-key-file=/var/run/serving-certs/tls.key
        - --prometheus-url=http://localhost:9090
        - --metrics-relist-interval=1m
        #- --rate-interval=30s
        - --discovery-interval=10m
        - --v=4
        ports:
        - containerPort: 6443
          name: https
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/serving-certs
          name: serving-certs
          readOnly: true
      - image: prom/prometheus:v2.2.0-rc.0
        name: prometheus
        args:
        # point prometheus at the configuration that you mount in below
        - --query.max-concurrency=200
        - --web.max-connections=2048
        - --config.file=/etc/prometheus/prometheus.yml
        ports:
        # this port exposes the dashboard and the HTTP API
        - containerPort: 9090
          name: prom-web
          protocol: TCP
        volumeMounts:
        # you'll mount your ConfigMap volume at /etc/prometheus
        - mountPath: /etc/prometheus
          name: config-volume
      - image: prom/pushgateway
        name: pushgateway
        ports:
        - containerPort: 9091
          name: http
      volumes:
      # make your configmap available as a volume, so that you can
      # mount in the Prometheus config from earlier
      - name: config-volume
        configMap:
          name: prometheus
      - name: serving-certs
        secret:
          secretName: serving-cm-adapter
```

Apparently, the API of prometheus adapter has changed since end of June. Does anyone know how I can inform these arguments of my .yaml file to adapter now? Is there any example of using the adapter?

We would appreciate any help.

**Comment by metalmatze** [comment]
There was one PR that has introduced new configuration that also removed the flag you're looking for:

https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/46/files#diff-f9233f40676b92d0ec7c641e48a62f5dL79

In general I wouldn't advice anyone to run `:latest` container images in their cluster, due to everything moving on, but your configuration being stuck with older version.

You are welcome to take a look at the kube-prometheus configuration we have for this adapter:

https://github.com/coreos/prometheus-operator/blob/aecd73e07e67740402196cc20e057f2f1a936224/contrib/kube-prometheus/manifests/prometheus-adapter-deployment.yaml#L17-L23

**Comment by dinhnhobao** [comment]
I got the same issue. 


`I0223 04:46:36.353569       1 adapter.go:98] successfully using in-cluster auth
F0223 04:46:36.353656       1 adapter.go:272] unable to load metrics discovery config: no metrics discovery configuration file specified (make sure to use --config)
goroutine 1 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.stacks(0xc00012a001, 0xc000686000, 0xa5, 0x1ba)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.(*loggingT).output(0x2ebed60, 0xc000000003, 0x0, 0x0, 0xc000497c70, 0x2de8877, 0xa, 0x110, 0x0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.(*loggingT).printf(0x2ebed60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1dd0509, 0x2b, 0xc0002a0780, 0x1, ...)
`

**Comment by dgrisonnet** [comment]
@dinhnhobao would you mind opening a separate issue? This one is quite old and both the adapter and kubernetes have changed a lot since.
