### ISSUE TITLE
"the server is currently unable to handle the request"

### ISSUE THREAD

**Issue by b0nete** [kubernetes-sigs/prometheus-adapter#315]
Hi guys, i'm trying using prometheus-adapter for publish metrics in my kubernetes cluster from my prometheus.

I've deployed prometheus-cloudwatch-exporter and im sending metrics to prometheus; i can see the metrics with this format:

```
aws_elasticache_curr_connections_average{cache_cluster_id=service-dev-001",exported_job="aws_elasticache",instance="prometheus-cloudwatch-exporter-dev:9106",job="monitoring/prometheus-cloudwatch-exporter"}
aws_elasticache_curr_connections_average{cache_cluster_id=service-dev-002",exported_job="aws_elasticache",instance="prometheus-cloudwatch-exporter-dev:9106",job="monitoring/prometheus-cloudwatch-exporter"}
```

The follow are my prometheus-adapter values deployed with helm3 in monitoring namespace:
```
rules:
  default: false
  custom:
  - seriesQuery: 'aws_elasticache_curr_connections_average{cache_cluster_id!=""}'
    resources:
      template: "<<.Resource>>"
    name:
      matches: ""
      as: "aws_elasticache"
    metricsQuery: rate(aws_elasticache_curr_connections_average{cache_cluster_id!=""}[2m])
  external:
  - seriesQuery: '{__name__=~"aws_elasticache_curr_connections_average"}'
    resources:
      template: "<<.Resource>>"
    name:
      matches: ""
      as: "aws_elasticache"
    metricsQuery: rate(aws_elasticache_curr_connections_average{cache_cluster_id!=""}[2m])
```

I tested this using custom and external metrics;
For some reason i cant get that work with external metrics with exactly the same rules.

This is an output querying  the server.
```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "jobs.batch/aws_elasticache",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}


kubectl get --raw /apis/external.metrics.k8s.io/v1beta1/ | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
```

So,  when i try get custom metrics but obtain the follor error:
```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/aws_elasticache | jq
Error from server (ServiceUnavailable): the server is currently unable to handle the reques
```

And in the prometheus-adapter logs i can see this.
```
I0922 20:32:38.276278       1 httplog.go:90] GET /apis/external.metrics.k8s.io/v1beta1?timeout=32s: (400.471µs) 200
[kubectl/v1.18.6 (linux/amd64) kubernetes/dff82dc 10.11.139.45:57738]
I0922 20:32:38.486127       1 httplog.go:90] GET /apis/external.metrics.k8s.io/v1beta1?timeout=32s: (338.936µs) 200 [kubectl/v1.18.6 (linux/amd64) kubernetes/dff82dc 10.11.139.45:57738]
I0922 20:32:39.943959       1 httplog.go:90] GET /healthz: (2.425632ms) 200 [kube-probe/1.15+ 10.11.189.88:6602]
I0922 20:32:44.519611       1 panic.go:679] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/aws_elasticache: (421.701µs) 0 [kubectl/v1.18.6 (linux/amd64) kubernetes/dff82dc 10.11.251.221:49814]
E0922 20:32:44.519679       1 runtime.go:76] Observed a panic: runtime error: slice bounds out of range [2:1]
goroutine 16507 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc000b09260)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x199e480, 0xc0005110a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.getRequestOptions(0xc000938100, 0x1dacec0, 0xc000276cc0, 0x1d94fc0, 0xc0005fb500, 0x1d75800, 0xc000276a40, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers/get.go:160 +0x622
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.ListResourceWithOptions.func1(0x1d92fc0, 0xc0002723b0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers/get.go:111 +0x501
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer.restfulListResourceWithOptions.func1(0xc0007c9230, 0xc000742700)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:294 +0xd8
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc0007c9230, 0xc000742700)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:337 +0x254
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc00054de60, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:288 +0xa4f
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:199
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1ac73ea, 0x1a, 0xc00054de60, 0xc00021cee0, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x4d3
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x512
net/http.HandlerFunc.ServeHTTP(0xc000276180, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x5dc
net/http.HandlerFunc.ServeHTTP(0xc000393b00, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1fe6
net/http.HandlerFunc.ServeHTTP(0xc0002761c0, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fb6d33f3e38, 0xc0002723a0, 0xc000938000)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:131 +0xa8c
net/http.HandlerFunc.ServeHTTP(0xc000271f40, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc000b09260, 0xc0008a4ec0, 0x1d9e200, 0xc0002723a0, 0xc000938000)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb

goroutine 16506 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17cd020, 0xc0009a3300)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc000469c90, 0x1, 0x1)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x17cd020, 0xc0009a3300)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc0008a4ec0, 0x1d93180, 0xc000742690, 0xc000938000)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:119 +0x486
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x1d93180, 0xc000742690, 0xc00094bf00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc000393b30, 0x1d93180, 0xc000742690, 0xc00094bf00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x1d93180, 0xc000742690, 0xc00094be00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc000393b60, 0x1d93180, 0xc000742690, 0xc00094be00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x1d87100, 0xc000272380, 0xc00094bd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc0008a4ee0, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x1d87100, 0xc000272380, 0xc00094bd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc0008a4f00, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000393b90, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0003dc8c0, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x1d9ddc0, 0xc00054b860, 0xc0006ea000, 0xc0003dc8c0, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/usr/local/go/src/net/http/server.go:3366 +0x8d
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00066be00, 0xc000272380, 0xc00094bd00, 0xc000936060)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2149 +0x9f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:1883 +0x4eb
E0922 20:32:44.519705       1 wrap.go:39] apiserver panic'd on GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/aws_elasticache
I0922 20:32:44.519806       1 log.go:172] http2: panic serving 10.11.251.221:49814: runtime error: slice bounds out of range [2:1]
goroutine 16507 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc000b09260)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x199e480, 0xc0005110a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.getRequestOptions(0xc000938100, 0x1dacec0, 0xc000276cc0, 0x1d94fc0, 0xc0005fb500, 0x1d75800, 0xc000276a40, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers/get.go:160 +0x622
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.ListResourceWithOptions.func1(0x1d92fc0, 0xc0002723b0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers/get.go:111 +0x501
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer.restfulListResourceWithOptions.func1(0xc0007c9230, 0xc000742700)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:294 +0xd8
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc0007c9230, 0xc000742700)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:337 +0x254
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc00054de60, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:288 +0xa4f
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:199
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1ac73ea, 0x1a, 0xc00054de60, 0xc00021cee0, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x4d3
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x512
net/http.HandlerFunc.ServeHTTP(0xc000276180, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x5dc
net/http.HandlerFunc.ServeHTTP(0xc000393b00, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1fe6
net/http.HandlerFunc.ServeHTTP(0xc0002761c0, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fb6d33f3e38, 0xc0002723a0, 0xc000938000)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:131 +0xa8c
net/http.HandlerFunc.ServeHTTP(0xc000271f40, 0x7fb6d33f3e38, 0xc0002723a0, 0xc000938000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc000b09260, 0xc0008a4ec0, 0x1d9e200, 0xc0002723a0, 0xc000938000)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb

goroutine 16506 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc000272380, 0xc000469f67, 0xc00066be00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2142 +0x16b
panic(0x17cd020, 0xc0009a3300)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc000469c90, 0x1, 0x1)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x17cd020, 0xc0009a3300)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc0008a4ec0, 0x1d93180, 0xc000742690, 0xc000938000)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:119 +0x486
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x1d93180, 0xc000742690, 0xc00094bf00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc000393b30, 0x1d93180, 0xc000742690, 0xc00094bf00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x1d93180, 0xc000742690, 0xc00094be00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc000393b60, 0x1d93180, 0xc000742690, 0xc00094be00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x1d87100, 0xc000272380, 0xc00094bd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc0008a4ee0, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x1d87100, 0xc000272380, 0xc00094bd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc0008a4f00, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000393b90, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0003dc8c0, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x1d9ddc0, 0xc00054b860, 0xc0006ea000, 0xc0003dc8c0, 0x1d87100, 0xc000272380, 0xc00094bd00)
	/usr/local/go/src/net/http/server.go:3366 +0x8d
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00066be00, 0xc000272380, 0xc00094bd00, 0xc000936060)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2149 +0x9f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:1883 +0x4eb
I0922 20:32:46.494668       1 httplog.go:90] GET /apis/custom.metrics.k8s.io/v1beta1?timeout=32s: (402.505µs) 200 [aws-k8s-agent/v0.0.0 (linux/amd64) kubernetes/$Format 10.11.251.221:49814]
I0922 20:32:46.497480       1 httplog.go:90] GET /apis/external.metrics.k8s.io/v1beta1?timeout=32s: (409.627µs) 200 [aws-k8s-agent/v0.0.0 (linux/amd64) kubernetes/$Format 10.11.251.221:49814]
I0922 20:32:46.991727       1 httplog.go:90] GET /apis/external.metrics.k8s.io/v1beta1: (219.5µs) 200 [Go-http-client/2.0 10.11.139.45:57712]
I0922 20:32:46.991762       1 httplog.go:90] GET /apis/custom.metrics.k8s.io/v1beta1: (343.365µs) 200 [Go-http-client/2.0 10.11.139.45:57712]
I0922 20:32:46.991763       1 httplog.go:90] GET /apis/custom.metrics.k8s.io/v1beta1: (347.048µs) 200 [Go-http-client/2.0 10.11.139.45:57712]
I0922 20:32:46.991764       1 httplog.go:90] GET /apis/custom.metrics.k8s.io/v1beta1: (270.447µs) 200 [Go-http-client/2.0 10.11.139.45:57712]
I0922 20:32:46.991987       1 httplog.go:90] GET /apis/external.metrics.k8s.io/v1beta1: (200.654µs) 200 [Go-http-client/2.0 10.11.139.45:57712]
I0922 20:32:46.991994       1 httplog.go:90] GET /apis/external.metrics.k8s.io/v1beta1: (186.232µs) 200 [Go-http-client/2.0 10.11.139.45:57712]
```

Versions: 
 - prometheus-cloudwatch-exporter-0.9.0
 - prometheus-adapter-2.5.2
 - EKS 1.15

I hope for your help me, thanks!

**Comment by mjroson** [comment]
I have the same problem. Any idea?

**Comment by Oxyaction** [comment]
have the same problem on namespaced-only requests

**Comment by arielvinas** [comment]
https://keda.sh/ squab...

**Comment by harrisjoseph** [comment]
I've hit the same problem with custom metrics where `"namespaced": false`, namespaced metrics are fine.

I assume i'm not formatting the request path correctly. I can't find any docs in the custom-metrics-apiserver repo that describe the expected request format for non-namespaced metrics. I'd expect this, but could be very very wrong:
```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/{namespace}/{metric_name}
```

**Comment by Oxyaction** [comment]
I've resolved my issue with specifying the correct query path

initially used
```
/apis/custom.metrics.k8s.io/v1beta1/namespaces/{namespace}/{metric_name}
```
while the correct URL is 
```
/apis/custom.metrics.k8s.io/v1beta1/namespaces/{namespace}/metrics/{metric_name}
```

It mentioned in 
https://github.com/DirectXMan12/k8s-prometheus-adapter#i-get-errors-when-query-namespace-prefixed-metrics

**Comment by harrisjoseph** [comment]
Using the correct URL has, as you might hope, fixed this issue.

This is the wrong place to ask this, but has anyone seen the expected metrics-apiserver API url scheme documented anywhere? Do people need to generate openapi docs themselves to find out which routes are exposed by a metrics-apiserver implementation?

I see nothing in the spec & reference implementations:
* https://github.com/kubernetes/metrics
* https://github.com/kubernetes-sigs/custom-metrics-apiserver

**Comment by dgrisonnet** [comment]
@harrisjoseph you should be able to get information about the custom and external metrics APIs at the beginning of the README.

There are the following links to the design documents of both APIs:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/external-metrics-api.md
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/custom-metrics-api.md

Would you suggest any change to the README to make these links more visible?

**Comment by harrisjoseph** [comment]
I'm sorry if my question was in any way offensive. Thanks for the links to those design proposals 🙂

**Comment by dgrisonnet** [comment]
It was not offensive at all, sorry if I conveyed a wrong feeling here, I didn't mean it. I just wanted to point out where this information is in the documentation. I think your question is very valid and I wouldn't be surprised if other users have the same interrogations, so I was trying to see if we could improve the documentation.
