### ISSUE TITLE
F0213 04:07:58.686760       1 adapter.go:304] unable to run custom metrics adapter: error creating self-signed certificates: mkdir apiserver.local.config: permission denied

### ISSUE THREAD

**Issue by patpatpat123** [kubernetes-sigs/prometheus-adapter#370]
Hello Prometheus Adapter Team,

First of all, a big thank you for this very cool project.
I am just facing a small issue, hence reporting it, hope not to trouble.

On container startup, I am facing an error loop, where I believe the root cause might be:

```
I0213 04:07:58.131298       1 request.go:1107] Response Body: {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"apiextensions.k8s.io/v1beta1","resources":[{"name":"customresourcedefinitions","singularName":"","namespaced":false,"kind":"CustomResourceDefinition","verbs":["create","delete","deletecollection","get","list","patch","update","watch"],"shortNames":["crd","crds"],"storageVersionHash":"jfWCUmvA="},{"name":"customresourcedefinitions/status","singularName":"","namespaced":false,"kind":"CustomResourceDefinition","verbs":["get","patch","update"]}]}
F0213 04:07:58.686760       1 adapter.go:304] unable to run custom metrics adapter: error creating self-signed certificates: mkdir apiserver.local.config: permission denied
goroutine 1 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc00018d700, 0xad, 0xfe)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.(*loggingT).output(0x2ebed60, 0xc000000003, 0x0, 0x0, 0xc0004080e0, 0x2de8877, 0xa, 0x130, 0x0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.(*loggingT).printf(0x2ebed60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1dc9ac5, 0x28, 0xc000994b00, 0x1, ...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:750 +0x191
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.Fatalf(...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:1502
main.main()
	/go/src/github.com/directxman12/k8s-prometheus-adapter/cmd/adapter/adapter.go:304 +0x9af

goroutine 6 [chan receive]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2ebed60)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.init.0
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 91 [IO wait]:
internal/poll.runtime_pollWait(0x7f4008689cb0, 0x72, 0x2003fa0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000b0e518, 0x72, 0x2003f00, 0x2e23690, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000b0e500, 0xc000290000, 0x73fe, 0x73fe, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000b0e500, 0xc000290000, 0x73fe, 0x73fe, 0x203000, 0x630a5b, 0xc000736160)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000206470, 0xc000290000, 0x73fe, 0x73fe, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000d1cf00, 0xc000290000, 0x73fe, 0x73fe, 0x218, 0x739e, 0xc00052b710)
	/usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc000736280, 0x1fffb20, 0xc000d1cf00, 0x40b605, 0x1b54320, 0x1d18be0)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000736000, 0x2002220, 0xc000206470, 0x5, 0xc000206470, 0x207)
	/usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000736000, 0x0, 0x0, 0xc00052bd18)
	/usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc000736000, 0xc000542000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0003e1c20, 0xc0005d8118, 0x9, 0x9, 0xc00052bd18, 0x1e6c500, 0x9d290b)
	/usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1fff980, 0xc0003e1c20, 0xc0005d8118, 0x9, 0x9, 0x9, 0xc0000a6060, 0x0, 0x1fffd40)
	/usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:333
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.readFrameHeader(0xc0005d8118, 0x9, 0x9, 0x1fff980, 0xc0003e1c20, 0x0, 0x0, 0xc00052bdd0, 0x46c805)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/frame.go:237 +0x89
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0005d80e0, 0xc000dde8a0, 0x0, 0x0, 0x0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00052bfa8, 0x0, 0x0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000683080)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

goroutine 48 [select]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1e6b5b0, 0x20014c0, 0xc0004cc8a0, 0x1, 0xc0000be0c0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1e6b5b0, 0x12a05f200, 0x0, 0xc0005ae201, 0xc0000be0c0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x1e6b5b0, 0x12a05f200)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/component-base/logs.InitLogs
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a

goroutine 533 [IO wait]:
internal/poll.runtime_pollWait(0x7f4008689bc8, 0x77, 0xc000545080)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0004b9d18, 0x77, 0x2053800, 0xc0005af1a0, 0xc0004b9d00)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitWrite(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:96
internal/poll.(*FD).WaitWrite(...)
	/usr/local/go/src/internal/poll/fd_unix.go:508
net.(*netFD).connect(0xc0004b9d00, 0x2053860, 0xc0005af1a0, 0x0, 0x0, 0x20027c0, 0xc0007b41c0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:141 +0x25c
net.(*netFD).dial(0xc0004b9d00, 0x2053860, 0xc0005af1a0, 0x205c900, 0x0, 0x205c900, 0xc0005fe270, 0x0, 0xc0001d8501, 0xc000d0f408)
	/usr/local/go/src/net/sock_posix.go:149 +0x108
net.socket(0x2053860, 0xc0005af1a0, 0x1d918ae, 0x3, 0x2, 0x1, 0x0, 0x0, 0x205c900, 0x0, ...)
	/usr/local/go/src/net/sock_posix.go:70 +0x1c5
net.internetSocket(0x2053860, 0xc0005af1a0, 0x1d918ae, 0x3, 0x205c900, 0x0, 0x205c900, 0xc0005fe270, 0x1, 0x0, ...)
	/usr/local/go/src/net/ipsock_posix.go:141 +0x145
net.(*sysDialer).doDialTCP(0xc0004b9c80, 0x2053860, 0xc0005af1a0, 0x0, 0xc0005fe270, 0x1b2c040, 0x2ef0608, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:65 +0xc5
net.(*sysDialer).dialTCP(0xc0004b9c80, 0x2053860, 0xc0005af1a0, 0x0, 0xc0005fe270, 0xc000d0f648, 0x405770, 0x60)
	/usr/local/go/src/net/tcpsock_posix.go:61 +0xd7
net.(*sysDialer).dialSingle(0xc0004b9c80, 0x2053860, 0xc0005af1a0, 0x202fda0, 0xc0005fe270, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:580 +0x5e5
net.(*sysDialer).dialSerial(0xc0004b9c80, 0x2053860, 0xc0005af1a0, 0xc000e140b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:548 +0x152
net.(*Dialer).DialContext(0xc0000ba2a0, 0x2053820, 0xc000058080, 0x1d918ae, 0x3, 0xc0007b4080, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:425 +0x6e5
net/http.(*Transport).dial(0x2ea6aa0, 0x2053820, 0xc000058080, 0x1d918ae, 0x3, 0xc0007b4080, 0x12, 0x0, 0xc000d0fab0, 0x756ea16a56a621, ...)
	/usr/local/go/src/net/http/transport.go:1141 +0x1fd
net/http.(*Transport).dialConn(0x2ea6aa0, 0x2053820, 0xc000058080, 0x0, 0xc0000d8180, 0x4, 0xc0007b4080, 0x12, 0x0, 0xc00038b8c0, ...)
	/usr/local/go/src/net/http/transport.go:1575 +0x1abb
net/http.(*Transport).dialConnFor(0x2ea6aa0, 0xc00023e000)
	/usr/local/go/src/net/http/transport.go:1421 +0xc6
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1390 +0x40f

goroutine 489 [chan receive]:
github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider.(*cachingMetricsLister).updateMetrics(0xc0000bc410, 0x203000, 0x7f40086f3a10)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider/provider.go:272 +0x31a
github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider.(*cachingMetricsLister).RunUntil.func1()
	/go/src/github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider/provider.go:226 +0x2a
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000994140)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000994140, 0x20014c0, 0xc0005fe000, 0x1, 0xc0000be0c0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000994140, 0x6fc23ac00, 0x0, 0xc0005a3801, 0xc0000be0c0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000994140, 0x6fc23ac00, 0xc0000be0c0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider.(*cachingMetricsLister).RunUntil
	/go/src/github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider/provider.go:225 +0x85

goroutine 534 [select]:
net.(*netFD).connect.func2(0x2053860, 0xc0005af1a0, 0xc0004b9d00, 0xc000aa8240, 0xc000aa81e0)
	/usr/local/go/src/net/fd_unix.go:118 +0xc5
created by net.(*netFD).connect
	/usr/local/go/src/net/fd_unix.go:117 +0x234

goroutine 532 [select]:
net/http.(*Transport).getConn(0x2ea6aa0, 0xc00081a000, 0x0, 0xc0000d8180, 0x4, 0xc0007b4080, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1347 +0x5ac
net/http.(*Transport).roundTrip(0x2ea6aa0, 0xc000c3e300, 0x0, 0x269, 0xc0008f9658)
	/usr/local/go/src/net/http/transport.go:569 +0x77c
net/http.(*Transport).RoundTrip(0x2ea6aa0, 0xc000c3e300, 0x2ea6aa0, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc000c3e300, 0x20022e0, 0x2ea6aa0, 0x0, 0x0, 0x0, 0xc00059e020, 0x203000, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:252 +0x453
net/http.(*Client).send(0x2ebdfc0, 0xc000c3e300, 0x0, 0x0, 0x0, 0xc00059e020, 0x0, 0x1, 0xf8)
	/usr/local/go/src/net/http/client.go:176 +0xff
net/http.(*Client).do(0x2ebdfc0, 0xc000c3e300, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:586
github.com/directxman12/k8s-prometheus-adapter/pkg/client.(*httpAPIClient).Do(0xc0002f3370, 0x2053820, 0xc000058088, 0x1d915de, 0x3, 0x1d9dcae, 0xe, 0xc0005fe060, 0x0, 0x0, ...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/pkg/client/api.go:62 +0x2d6
github.com/directxman12/k8s-prometheus-adapter/pkg/client/metrics.(*instrumentedGenericClient).Do(0xc000202ae0, 0x2053820, 0xc000058088, 0x1d915de, 0x3, 0x1d9dcae, 0xe, 0xc0005fe060, 0x0, 0x0, ...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/pkg/client/metrics/metrics.go:69 +0x1aa
github.com/directxman12/k8s-prometheus-adapter/pkg/client.(*queryClient).Series(0xc0002f3380, 0x2053820, 0xc000058088, 0x17799927486, 0x0, 0xc000e14010, 0x1, 0x1, 0xc000468060, 0xc000d85f30, ...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/pkg/client/api.go:160 +0x1c8
github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider.(*cachingMetricsLister).updateMetrics.func1(0xc0000bc410, 0x17799927486, 0xc000478ac0, 0x1c, 0xc0005ae120, 0xc0005ae000)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider/provider.go:257 +0xe2
created by github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider.(*cachingMetricsLister).updateMetrics
	/go/src/github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider/provider.go:256 +0x9b2

```

When I create the adapter, I am doing it via this way:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-metrics-apiserver
  name: custom-metrics-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      serviceAccountName: default
      containers:
        - name: custom-metrics-apiserver
          image: directxman12/k8s-prometheus-adapter-amd64
          args:
            - /adapter
            - --secure-port=6443
            - --logtostderr=true
            - --prometheus-url=http://my-prometheus:80/
            - --metrics-relist-interval=30s
            - --v=10
            - --config=/etc/adapter/config.yaml
          ports:
            - containerPort: 6443
          volumeMounts:
            - mountPath: /etc/adapter/
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: adapter-config
```

In order to make the flow work, the prometheus who is exposing the metrics is accessible over http.
I can curl and wget the ``` - --prometheus-url=http://my-prometheus:80/ ``` and see all custom metrics, alongside the metric HPA should happen on.

It is over plain http, I believe certificates are not needed.

I was wondering, what might be the root cause of this permission denied please?
What can I also do to fix it please?

Thank you!

**Comment by dgrisonnet** [comment]
Hello @patpatpat123, thank you for the kind words!

These certs are meant for communication with the apiserver, not Prometheus.
In your case, it seems that you are not allowed to create files in the default directory used by the adapter. You can change that via the `--cert-dir` option. For example, you could set it to `/var/run/serving-cert` as we are doing in kube-prometheus or to `/tmp` if you are running prometheus-adapter in a restricted environment.
