### ISSUE TITLE
message:unable to list matching resources, code:500 when trying to access custom metrics

### ISSUE THREAD

**Issue by karolmigo** [kubernetes-sigs/prometheus-adapter#471]
**What happened?**:

Tried to list custom metrics with a following command: ``` kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/staging/*/http_requests" | jq .```

**What did you expect to happen?**:

Get me a list of metrics.

**Anything else we need to know?**:

The get call crashed with: 

```
I1130 08:36:52.765151       1 httplog.go:104] "HTTP" verb="GET" URI="/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/staging/%2A/http_requests" latency="2.663856ms" userAgent="kubectl/v1.21.3 (darwin/amd64) kubernetes/ca643a4" audit-ID="ed8b7b0d-94be-4a63-8568-12a184c5c853" srcIP="172.18.21.195:55938" resp=500 statusStack="\ngoroutine 565282 [running]:\nk8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc003c48100, 0x1f4)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/httplog/httplog.go:274 +0xcf\nk8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc003c48100, 0x1f4)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/httplog/httplog.go:252 +0x35\nk8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc003c46040, 0x1f4)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/filters/timeout.go:227 +0xb2\nk8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc003c3e480, 0x1f4)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/metrics/metrics.go:603 +0x45\nk8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc000550ba0, 0xc0016b0000, 0xf7, 0x148, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/handlers/responsewriters/writers.go:228 +0x2fd\nencoding/json.(*Encoder).Encode(0xc0017975b8, 0x206cfc0, 0xc000332460, 0x7c13fa, 0x235082a)\n\t/usr/local/go/src/encoding/json/stream.go:231 +0x1df\nk8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0xc0000966e0, 0x2386eb0, 0xc000332460, 0x237aba0, 0xc000550ba0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.0/pkg/runtime/serializer/json/json.go:327 +0x2e9\nk8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc0000966e0, 0x2386eb0, 0xc000332460, 0x237aba0, 0xc000550ba0, 0x1beadad, 0x6)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.0/pkg/runtime/serializer/json/json.go:301 +0x169\nk8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc000332500, 0x2386eb0, 0xc000332460, 0x237aba0, 0xc000550ba0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.0/pkg/runtime/serializer/versioning/versioning.go:228 +0x3b6\nk8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc000332500, 0x2386eb0, 0xc000332460, 0x237aba0, 0xc000550ba0, 0xc000103680, 0x3)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.0/pkg/runtime/serializer/versioning/versioning.go:184 +0x170\nk8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x20ce8b4, 0x10, 0x7f4a1197d718, 0xc000332500, 0x23b77a0, 0xc004ccc048, 0xc0037f8b00, 0x1f4, 0x2386eb0, 0xc000332460)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/handlers/responsewriters/writers.go:106 +0x457\nk8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x23b9330, 0xc0005da140, 0x23b94b0, 0x31c7030, 0x20d61f9, 0x15, 0x20c3567, 0x7, 0x23b77a0, 0xc004ccc048, ...)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/handlers/responsewriters/writers.go:275 +0x5cd\nk8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x237a6c0, 0xc0003323c0, 0x23b9330, 0xc0005da140, 0x20d61f9, 0x15, 0x20c3567, 0x7, 0x23b77a0, 0xc004ccc048, ...)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/handlers/responsewriters/writers.go:294 +0x16f\nsigs.k8s.io/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.writeError(...)\n\t/go/pkg/mod/sigs.k8s.io/custom-metrics-apiserver@v1.22.0/pkg/apiserver/endpoints/handlers/rest.go:33\nsigs.k8s.io/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.ListResourceWithOptions.func1(0x23b77a0, 0xc004ccc048, 0xc0037f8b00)\n\t/go/pkg/mod/sigs.k8s.io/custom-metrics-apiserver@v1.22.0/pkg/apiserver/endpoints/handlers/get.go:118 +0xce8\nsigs.k8s.io/custom-metrics-apiserver/pkg/apiserver/installer.restfulListResourceWithOptions.func1(0xc003c3e3f0, 0xc0001d0000)\n\t/go/pkg/mod/sigs.k8s.io/custom-metrics-apiserver@v1.22.0/pkg/apiserver/installer/installer.go:297 +0xed\nk8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc003c3e3f0, 0xc0001d0000)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/metrics/metrics.go:484 +0x2d5\ngithub.com/emicklei/go-restful.(*Container).dispatch(0xc000263560, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/github.com/emicklei/go-restful@v2.15.0+incompatible/container.go:294 +0x65a\ngithub.com/emicklei/go-restful.(*Container).Dispatch(...)\n\t/go/pkg/mod/github.com/emicklei/go-restful@v2.15.0+incompatible/container.go:204\nk8s.io/apiserver/pkg/server.director.ServeHTTP(0x20ddf36, 0x1a, 0xc000263560, 0xc0003b9ce0, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/handler.go:146 +0x63e\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filterlatency/filterlatency.go:103 +0x193\nnet/http.HandlerFunc.ServeHTTP(0xc0005f2870, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filters/authorization.go:64 +0x603\nnet/http.HandlerFunc.ServeHTTP(0xc0006a7880, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filterlatency/filterlatency.go:79 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0006a78c0, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/filters/maxinflight.go:187 +0x676\nnet/http.HandlerFunc.ServeHTTP(0xc0005f28a0, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filterlatency/filterlatency.go:103 +0x193\nnet/http.HandlerFunc.ServeHTTP(0xc0005f28d0, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filters/impersonation.go:50 +0x274d\nnet/http.HandlerFunc.ServeHTTP(0xc0006a7940, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filterlatency/filterlatency.go:79 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0006a7980, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filterlatency/filterlatency.go:103 +0x193\nnet/http.HandlerFunc.ServeHTTP(0xc0005f2900, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filterlatency/filterlatency.go:79 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0006a79c0, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filterlatency/filterlatency.go:103 +0x193\nnet/http.HandlerFunc.ServeHTTP(0xc0005f2960, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filters.withAuthentication.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8b00)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filters/authentication.go:80 +0x75c\nnet/http.HandlerFunc.ServeHTTP(0xc0005f16e0, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8900)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7f4a114df470, 0xc004ccc010, 0xc0037f8800)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/endpoints/filterlatency/filterlatency.go:88 +0x38c\nnet/http.HandlerFunc.ServeHTTP(0xc0006a7a00, 0x7f4a114df470, 0xc004ccc010, 0xc0037f8800)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nk8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0006b26c0, 0xc00054df20, 0x23bc678, 0xc004ccc010, 0xc0037f8800)\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/filters/timeout.go:108 +0xb8\ncreated by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP\n\t/go/pkg/mod/k8s.io/apiserver@v0.22.0/pkg/server/filters/timeout.go:94 +0x1fa\n" addedInfo="\nlogging error output: \"{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Internal error occurred: unable to list matching resources\\\",\\\"reason\\\":\\\"InternalError\\\",\\\"details\\\":{\\\"causes\\\":[{\\\"message\\\":\\\"unable to list matching resources\\\"}]},\\\"code\\\":500}\\n\"\n"
```

**Environment**:
- prometheus-adapter version: 0.9.1 
- prometheus version: 2.11
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: aws

**Comment by prashbnair** [comment]
Could you share your adapter config file?
